// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    owner_id,
    name,
    mime,
    is_file,
    is_public,
    json_data,
    storage_key,
    size_bytes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id
`

type CreateDocumentParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	Name       string      `json:"name"`
	Mime       string      `json:"mime"`
	IsFile     bool        `json:"is_file"`
	IsPublic   bool        `json:"is_public"`
	JsonData   []byte      `json:"json_data"`
	StorageKey pgtype.Text `json:"storage_key"`
	SizeBytes  int64       `json:"size_bytes"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.OwnerID,
		arg.Name,
		arg.Mime,
		arg.IsFile,
		arg.IsPublic,
		arg.JsonData,
		arg.StorageKey,
		arg.SizeBytes,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createDocumentGrant = `-- name: CreateDocumentGrant :exec
INSERT INTO document_grants (
    document_id,
    user_id
)
VALUES (
    $1,
    $2
)
`

type CreateDocumentGrantParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateDocumentGrant(ctx context.Context, arg CreateDocumentGrantParams) error {
	_, err := q.db.Exec(ctx, createDocumentGrant, arg.DocumentID, arg.UserID)
	return err
}
