// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    owner_id,
    name,
    mime,
    is_file,
    is_public,
    json_data,
    storage_key,
    size_bytes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id
`

type CreateDocumentParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	Name       string      `json:"name"`
	Mime       string      `json:"mime"`
	IsFile     bool        `json:"is_file"`
	IsPublic   bool        `json:"is_public"`
	JsonData   []byte      `json:"json_data"`
	StorageKey pgtype.Text `json:"storage_key"`
	SizeBytes  int64       `json:"size_bytes"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.OwnerID,
		arg.Name,
		arg.Mime,
		arg.IsFile,
		arg.IsPublic,
		arg.JsonData,
		arg.StorageKey,
		arg.SizeBytes,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createDocumentGrant = `-- name: CreateDocumentGrant :exec
INSERT INTO document_grants (
    document_id,
    user_id
)
VALUES (
    $1,
    $2
)
`

type CreateDocumentGrantParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateDocumentGrant(ctx context.Context, arg CreateDocumentGrantParams) error {
	_, err := q.db.Exec(ctx, createDocumentGrant, arg.DocumentID, arg.UserID)
	return err
}

const deleteDocument = `-- name: DeleteDocument :one
DELETE FROM documents
WHERE id = $1::uuid
  AND owner_id = $2::uuid
RETURNING storage_key
`

type DeleteDocumentParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, deleteDocument, arg.DocumentID, arg.OwnerID)
	var storage_key pgtype.Text
	err := row.Scan(&storage_key)
	return storage_key, err
}

const getDocument = `-- name: GetDocument :one
SELECT
    d.id,
    d.mime,
    d.is_file,
    d.json_data,
    d.storage_key,
    (
        d.owner_id = $1::uuid
        OR d.is_public
        OR EXISTS (
            SELECT 1
            FROM document_grants dg
            WHERE dg.document_id = d.id
              AND dg.user_id = $1::uuid
        )
    )::boolean AS can_read
FROM documents d
WHERE d.id = $2::uuid
`

type GetDocumentParams struct {
	ViewerID   pgtype.UUID `json:"viewer_id"`
	DocumentID pgtype.UUID `json:"document_id"`
}

type GetDocumentRow struct {
	ID         pgtype.UUID `json:"id"`
	Mime       string      `json:"mime"`
	IsFile     bool        `json:"is_file"`
	JsonData   []byte      `json:"json_data"`
	StorageKey pgtype.Text `json:"storage_key"`
	CanRead    bool        `json:"can_read"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ViewerID, arg.DocumentID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Mime,
		&i.IsFile,
		&i.JsonData,
		&i.StorageKey,
		&i.CanRead,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT
    d.id::text AS id,
    d.name,
    d.mime,
    d.is_file,
    d.is_public,
    d.created_at,
    ARRAY(
        SELECT granted_user.login
        FROM document_grants AS dg
        JOIN users AS granted_user ON granted_user.id = dg.user_id
        WHERE dg.document_id = d.id
        ORDER BY granted_user.login
    )::text[] AS grants
FROM documents AS d
JOIN users AS owner_user ON owner_user.id = d.owner_id
WHERE owner_user.login = $1::text
  AND (
      d.owner_id = $2::uuid
      OR d.is_public
      OR EXISTS (
          SELECT 1
          FROM document_grants AS access_grant
          WHERE access_grant.document_id = d.id
            AND access_grant.user_id = $2::uuid
      )
  )
  AND (
      $3::text = ''
      OR CASE $3::text
          WHEN 'id' THEN d.id::text
          WHEN 'name' THEN d.name
          WHEN 'mime' THEN d.mime
          WHEN 'file' THEN d.is_file::text
          WHEN 'public' THEN d.is_public::text
      END = $4::text
  )
ORDER BY d.name ASC, d.created_at ASC, d.id ASC
LIMIT $5::integer
`

type ListDocumentsParams struct {
	OwnerLogin  string      `json:"owner_login"`
	ViewerID    pgtype.UUID `json:"viewer_id"`
	FilterKey   string      `json:"filter_key"`
	FilterValue string      `json:"filter_value"`
	ResultLimit int32       `json:"result_limit"`
}

type ListDocumentsRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Mime      string             `json:"mime"`
	IsFile    bool               `json:"is_file"`
	IsPublic  bool               `json:"is_public"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Grants    []string           `json:"grants"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.OwnerLogin,
		arg.ViewerID,
		arg.FilterKey,
		arg.FilterValue,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mime,
			&i.IsFile,
			&i.IsPublic,
			&i.CreatedAt,
			&i.Grants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
