// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID         pgtype.UUID        `json:"id"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
	Name       string             `json:"name"`
	Mime       string             `json:"mime"`
	IsFile     bool               `json:"is_file"`
	IsPublic   bool               `json:"is_public"`
	JsonData   []byte             `json:"json_data"`
	StorageKey pgtype.Text        `json:"storage_key"`
	SizeBytes  int64              `json:"size_bytes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type DocumentGrant struct {
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

type Session struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Login        string             `json:"login"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
