// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    token_hash,
    user_id,
    expires_at
)
VALUES (
    $1,
    $2,
    $3
)
`

type CreateSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT
    u.id,
    u.login
FROM sessions AS s
JOIN users AS u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetSessionUserRow struct {
	ID    pgtype.UUID `json:"id"`
	Login string      `json:"login"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(&i.ID, &i.Login)
	return i, err
}
