// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    login,
    password_hash
)
VALUES (
    $1,
    $2
)
RETURNING id, login, created_at
`

type CreateUserParams struct {
	Login        string `json:"login"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Login     string             `json:"login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Login, &i.CreatedAt)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password_hash
FROM users
WHERE login = $1
`

type GetUserByLoginRow struct {
	ID           pgtype.UUID `json:"id"`
	Login        string      `json:"login"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(&i.ID, &i.Login, &i.PasswordHash)
	return i, err
}

const getUsersByLogins = `-- name: GetUsersByLogins :many
SELECT id, login
FROM users
WHERE login = ANY($1::text[])
`

type GetUsersByLoginsRow struct {
	ID    pgtype.UUID `json:"id"`
	Login string      `json:"login"`
}

func (q *Queries) GetUsersByLogins(ctx context.Context, logins []string) ([]GetUsersByLoginsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByLogins, logins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByLoginsRow
	for rows.Next() {
		var i GetUsersByLoginsRow
		if err := rows.Scan(&i.ID, &i.Login); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
